name: Semgrep CE scan

on:
  pull_request: {}
  workflow_dispatch: {}
  push:
    branches: ["master", "main"]
  schedule:
    - cron: '35 8 * * *'  # Daily at 08:20 UTC

permissions:
  contents: read
  actions: read            # Needed for CodeQL SARIF processing
  security-events: write   # Required to upload results to the Security tab

jobs:
  semgrep:
    name: semgrep-oss/scan
    runs-on: ubuntu-latest

    container:
      image: semgrep/semgrep

    if: github.actor != 'dependabot[bot]'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Semgrep and generate SARIF
        run: |
          semgrep scan --config auto \
                       --sarif -o semgrep-results.sarif

      - name: Upload SARIF to GitHub Code Scanning
        if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep-results.sarif
